baseurl: "https://example.org/"
title: "Fourty Two Star"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "42* Event"
  Description: "42 The Answer"
  Date: "August 24"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Kulturwiese"
  Address: "Schreberweg 21"
  City:  "Darmstadt"
  State: "Hessen"
  Images: ["/img/badge.jpg"]
  #GoogleMapsKey: "sSPBUTYT6NXrCBjv9"
  #https://maps.app.goo.gl/sSPBUTYT6NXrCBjv9

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    #- sponsors
    - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "Info"
    location: "Location"
    speakers: "Events"
    schedule: "Ablauf"
    #sponsors: "Sponsors"
    partners: "Prologue"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Register now!"
  #  link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  #Sponsors:
  #  - name: "Hugo"
  #    logo: "/img/hugo.png"
  #    url: "http://gohugo.io"

  # List of Partners
  Partners:
    text: "The ulitimate text .. from A.Diroll"

  # The entire schedule
  Schedule:
    - name: "Starters"
      time: "13h00"

    - name: "Patch Some Cables"
      photo: "/img/slomosmo.png"
      bio: "Eine experimentelle Modular Synthesizer Chill Out Session."
      company: "Slomosmo & Friends"
      link:
        href: "https://soundcloud.com/slomosmo"
        text: "by slomosmo"
      presentation:
        title: "Modular Lab"
        description: "Slomosmo & Friends will do a great electronic live performance. This is a side project, playing music during the live painting sessions untill 17:00 o`clock round about."
        time: "13h00"

    - name: "37 Magics"
      photo: "/img/nick.png"
      bio: "Nick Marschalek und seine Freunde vom Neuzeit Kollektive malen freaky Bilder."
      company: "Nick Marschalek & Friends"
      link:
        href: "https://linktr.ee/nickmarschalek"
        text: "by nickmarschalek"
      presentation:
        title: "Live Painting"
        description: "Nick Marschalek & Friends will paint images during modular madness session and beyond. Additional there will be some other interactive painting possibilies .."
        time: "13h00"

    - name: "Print Some"
      photo: "/img/nino.jpg"
      bio: "Wer passende Klamotte mitbringt, kann bei Nino bedruckt werden."
      company: "Nino & Seine Maschinen"
      link:
        href: "https://www.instagram.com/streetheartcolor/"
        text: "by nino"
      presentation:
        title: "Nino's Siebdruck"
        description: "You can bring your own or buy some cloth from us to print predesigned artworks. If you like to prepare something in advance, let us know.."
        time: "13h00"

    - name: "Find Out What"
      photo: "/img/workshop2.jpg"
      bio: "Eine Option herauzufinden, was es herauszufinden gibt."
      company: "Unkown People"
      link:
        href: "https://en.wikipedia.org/wiki/37_(number)"
        text: "by whatever_37"
      presentation:
        title: "Missing Workshop"
        description: "You can bring your own or buy some cloth from us to print predesigned artworks. If you like to prepare something in advance, let us know.."
        time: "13h00"

    - name: "Theater"
      time: "14h00"

    - name: "Theater 1"
      photo: "/img/beyou.png"
      bio: "Theather Performance von A.Diroll & Johanna"
      company: "Be You Assemble"
      link:
        href: "https://www.p-stadtkultur.de/p-autoren/alex-diroll"
        text: "by beyouuuu"
      presentation:
        title: "Be U2"
        description: "@ Side Stage: Text zum Theaterstuck.."
        time: "14h00"

    - name: "Theater 2"
      photo: "/img/42new.png"
      bio: "Theather Performance von Fourtytwostar ..."
      company: "Fourtytwostar Assemble"
      link:
        href: "http://github.com/billy95"
        text: "by fourtytwostar"
      presentation:
        title: "Fourtytwostar"
        description: "@ Side Stage Text zum Theaterstuck.."
        time: "15h00"

    - name: "Live Music"
      time: "18h00"

    - name: "Psychodelic Krautrock"
      photo: "/img/lucidvoid.jpg"
      bio: "Psychodelic Rock aus Darmstadt"
      company: "Lucid Void"
      link:
        href: "https://lucidvoid.bandcamp.com"
        text: "@lucidvoid"
      presentation:
        title: "Lucid Void"
        description: "Band Text here .."
        time: "18h00"

    - name: "Soul & Rock Music"
      photo: "/img/tbsr.jpg"
      bio: "Finest Soul & Rock Music aus Darmstadt"
      company: "The Bad Sugar Rush"
      link:
        href: "https://www.facebook.com/badsugarrush"
        text: "@badsugarrush"
      presentation:
        title: "The Bad Sugar Rush"
        description: "Band Text here .."
        time: "19h30"

    - name: "Psychodelic Space Jazz"
      photo: "/img/karaba.jpg"
      bio: "Space Kraut Jazz aus München"
      company: "Karaba"
      link:
        href: "https://karaba-band.bandcamp.com/album/karaba-all-high-ways"
        text: "@karaba"
      presentation:
        title: "Karaba"
        description: "Band Text here .."
        time: "21h00"
