baseurl: "https://example.org/"
title: "Fourty Two Star"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "42* Event"
  Description: "42 The Answer"
  Date: "August 24"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Kulturwiese"
  Address: "Schreberweg 21"
  City:  "Darmstadt"
  State: "Hessen"
  Images: ["/img/badge.jpg"]
  #GoogleMapsKey: "sSPBUTYT6NXrCBjv9"
  #https://maps.app.goo.gl/sSPBUTYT6NXrCBjv9

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - partners
    - sponsors
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "Info"
    location: "Location"
    speakers: "Events"
    schedule: "Ablauf"
    partners: "Prolog"
    sponsors: "Kontakt"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Register now!"
  #  link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Max"
      logo: "/img/contact.png"
      url: "https://mxklb.github.io/42star"
    - name: "Link"
      logo: "/img/qrcode.png"
      url: "https://mxklb.github.io/42star"

  # List of Partners
  Partners:
    text: "The ulitimate text .. from A.Diroll"

  # The entire schedule
  Schedule:
    - name: "Starter"
      time: "13h00"

    - name: "Patch Some Cables"
      photo: "/img/slomosmo.png"
      bio: "Eine experimentelle Modular Synthesizer Chill Out Session."
      company: "Slomosmo"
      link:
        href: "https://soundcloud.com/slomosmo"
        text: "by slomosmo"
      presentation:
        title: "Modular Lab"
        description: "Slomosmo & Friends kredenzen euch eine wundervoll elektronische Live Session. Sie machen Musik zur Untermalung des Live Paintings bis in den Nachmittag hinein."
        time: "13h00"

    - name: "37 Magics"
      photo: "/img/nick.png"
      bio: "Nick Marschalek vom Neuzeit Kollektive malt bunte Bilder."
      company: "Nick Marschalek"
      link:
        href: "https://linktr.ee/nickmarschalek"
        text: "by nickmarschalek"
      presentation:
        title: "Live Painting"
        description: "Nick Marschalek vom Neuzeit Kollektiv malt bunte Bilder, begleitet von der Modular Synthesizer Session."
        time: "13h00"

    - name: "Print Some"
      photo: "/img/nino.jpg"
      bio: "Wer passende Klamotte mitbringt, kann bei Nino bedruckt werden."
      company: "Streetheartcolor"
      link:
        href: "https://www.instagram.com/streetheartcolor/"
        text: "by nino"
      presentation:
        title: "Nino's Siebdruck"
        description: "Eigene Klamotte mitbringen zum bedrucken, oder was bei Nino kaufen."
        time: "13h00"

    - name: "Make A Button"
      photo: "/img/button.jpg"
      bio: "Bastel dir deinen individuellen 42* Button."
      company: "Miss Button"
      link:
        href: "https://en.wikipedia.org/wiki/37_(number)"
        text: "by missbutton"
      presentation:
        title: "Button Workshop"
        description: "Ein 42* Button beantwortet generell auch alle Fragen."
        time: "13h00"

    - name: "Find Out What"
      photo: "/img/workshop2.jpg"
      bio: "Eine Option herauszufinden, was es herauszufinden gibt."
      company: "Unkown People"
      link:
        href: "https://en.wikipedia.org/wiki/37_(number)"
        text: "by whatever_37"
      presentation:
        title: "Missing Workshop"
        description: "Finde heraus, was es schon immer herauszufinden galt."
        time: "13h00"

    - name: "Theater"
      time: "14h00"

    - name: "Theater 1"
      photo: "/img/beyou.png"
      bio: "Theater Performance von A.Diroll & Johanna"
      company: "Be You Assemble"
      link:
        href: "https://www.p-stadtkultur.de/p-autoren/alex-diroll"
        text: "by beyouuuu"
      presentation:
        title: "Be You"
        description: "@ Side Stage: Text zum Theaterstück.."
        time: "14h00"

    - name: "Theater 2"
      photo: "/img/42new.png"
      bio: "Theater Performance von Fourtytwostar ..."
      company: "Fourtytwostar Assemble"
      link:
        href: "http://github.com/billy95"
        text: "by fourtytwostar"
      presentation:
        title: "Fourtytwo"
        description: "@ Side Stage Text zum Theaterstück.."
        time: "15h00"

    - name: "Live Musik"
      time: "18h00"

    - name: "Psychodelic Krautrock"
      photo: "/img/lucidvoid.jpg"
      bio: "Psychodelic Rock aus Darmstadt"
      company: "Psychodelic Krautrock"
      link:
        href: "https://lucidvoid.bandcamp.com"
        text: "@lucidvoid"
      presentation:
        title: "Lucid Void"
        description: "Band Text here .."
        time: "18h00"

    - name: "Soul & Rock Music"
      photo: "/img/tbsr.jpg"
      bio: "Finest Soul & Rock Music aus Darmstadt"
      company: "Soul & Rock"
      link:
        href: "https://www.facebook.com/badsugarrush"
        text: "@badsugarrush"
      presentation:
        title: "The Bad Sugar Rush"
        description: "Band Text here .."
        time: "19h30"

    - name: "Psychodelic Space Jazz"
      photo: "/img/karaba.jpg"
      bio: "Space Kraut Jazz aus München"
      company: "Psychodelic Space Jazz"
      link:
        href: "https://karaba-band.bandcamp.com/album/karaba-all-high-ways"
        text: "@karaba"
      presentation:
        title: "Karaba"
        description: "Band Text here .."
        time: "21h00"
