baseurl: "https://example.org/"
title: "Forty Two Star"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "42* Open Air"
  Description: "42* ist eine Kunst, Kultur & Open Air Live Musik Veranstaltung. Das Event findet von 13 - 22 Uhr auf der Kulturwiese in Darmstadt statt."
  Date: "24. August"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Kulturwiese"
  Address: "Kulturwiese"
  City:  "Darmstadt"
  State: "Darmstadt Nord"
  Coord: "49.893638, 8.662776"
  Images: ["/img/42-badge.png"]
  Logo: "/img/42-white.png"
  #Flyer: "/img/42.png"
  #GoogleMapsKey: "sSPBUTYT6NXrCBjv9"
  #https://maps.app.goo.gl/sSPBUTYT6NXrCBjv9

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    #- partners
    - sponsors
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "Info"
    location: "Location"
    speakers: "What's up"
    schedule: "Timetable"
    partners: "Prolog"
    sponsors: "References"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Register now!"
  #  link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Crew"
      logo: "/img/contact.png"
      url: "https://mxklb.github.io/42star"
    - name: "Link"
      logo: "/img/qrcode.png"
      url: "https://mxklb.github.io/42star"
    - name: "Flyer"
      logo: "/img/flyer-small.png"
      url: "https://mxklb.github.io/42star"

  # List of Partners
  Partners:
    text: "The ulitimate text/audio .. from A.Diroll"

  # The entire schedule
  Schedule:
    - name: "Auf der Wiese"
      time: "13-18"

    - name: "Patch Some Cables"
      photo: "/img/slomosmo.png"
      bio: "Eine experimentelle Modular Synth Soundscape Session"
      company: "Smo & Friends"
      link:
        href: "https://linktr.ee/slomosmo"
        text: "by Smo & Friends"
      presentation:
        title: "Modular Lab"
        description: "Das Modular Lab kredenzt euch eine wundervolle Live Session. Sie machen elektronische Musik zur Untermalung der Workshops, bis in den Nachmittag hinein."
        time: "13:00"

    - name: "37 Magics"
      photo: "/img/nick.png"
      bio: "Nick Marschalek vom Neuzeit Kollektiv malt nice Bilder"
      company: "Nick Marschalek"
      link:
        href: "https://linktr.ee/nickmarschalek"
        text: "by Nick Marschalek"
      presentation:
        title: "Live Painting"
        description: "Nick Marschalek vom Neuzeit Kollektiv malt, musikalisch untermalt vom Modular Lab, kreative Bilder. Er wird das Thema frei interpretieren."
        time: "13:00"

    - name: "Mal * Kunst"
      photo: "/img/interactive.png"
      bio: "Ob klein oder gross, alle werden wildes Zeug malen"
      company: "Das Publikum"
      link:
        href: ""
        text: "by Das Publikum"
      presentation:
        title: "Mit Mal Aktion"
        description: "Hier dürfen sich Klein und Gross gemeinsam künstlerisch austoben. Es geht nicht darum das Schönste, sondern was Verrücktes, die Antwort auf Alles, zu kreieren."
        time: "13:30"

    - name: "Print Some"
      photo: "/img/nino.jpg"
      bio: "Wer Klamotte sucht oder mitbringt, kann bei Nino bedruckt werden"
      company: "Streetheartcolor"
      link:
        href: "https://www.instagram.com/streetheartcolor/"
        text: "by Streetheartcolor"
      presentation:
        title: "Nino's Siebdruck"
        description: "Wer keine passende Klamotte zum bedrucken dabei hat, der findet bestimmt ein passend kolorierbares Teil im Streetheart Fundus :)"
        time: "13:37"

    - name: "Rituale"
      photo: "/img/orakel.png"
      bio: "Das Orakel wird dir einen Weg weisen"
      company: "Michi & Alex"
      link:
        href: "http://www.michael-marquardt.com/private.html"
        text: "by Michael Marquardt"
      presentation:
        title: "Das Orakel"
        description: "Wir sind das Orakel vom Platz. Das Orakel findet den ganzen Tag statt. Bring eine persönliche Frage mit. Und ein Geschenk. Die Antwort könnte dich überraschen."
        time: "13:42"

    #- name: "Organic Materials"
    #  photo: "/img/land-art.jpg"
    #  bio: "Kreiere 100% biologisch abbaubare Kunst"
    #  company: "Mira"
    #  link:
    #    href: ""
        #text: "by Mira"
    #  presentation:
    #    title: "Land Art"
    #    description: "Erschaffe Kunst auf Basis natürliche auffindbarer Rohstoffen"
    #    time: "14:00"

    - name: "Find Out What"
      photo: "/img/deep.jpg"
      bio: "Eine Option herauszufinden, was es herauszufinden gibt"
      company: "Mr. X"
      link:
        href: "https://en.wikipedia.org/wiki/37_(number)"
        text: "by Whatever 37"
      presentation:
        title: "Missing Workshop"
        description: "Finde heraus, was es schon immer herauszufinden galt."
        time: "13:99"

    - name: "Theater Bühne"
      time: "14-16"

    - name: "Theater"
      photo: "/img/beyou.png"
      bio: "Oder fällt dir sonst noch was dazu ein?"
      company: "Johanna & Alex"
      link:
        href: ""
        text: "von J. Schubert & E.A.Diroll"
      presentation:
        title: "Alles - Oh mein Gott - Scheiße?!"
        description: "Wenn Gott unsere WG besuchen würde,
würden wir ihm dann eine Banane anbieten
oder hochkantig rausschmeißen?
Was das mit unserer Katze und der Oma zu tun hat?
Wir werden es herausfinden."
        time: "14:00"

    - name: "Poetry Slam"
      photo: "/img/42.png"
      bio: "Die Antwort auf Alles und Fragen zum Nichts"
      company: "u.A. Johanna"
      link:
        href: "https://simple.wikipedia.org/wiki/42_(answer)"
        text: "Moderation by J. Schubert"
      presentation:
        title: "Die Antwort auf Alles"
        description: "Texte über Zukünftiges - ob politisch, irgendwas mit KI, dystoipisch, kafkaesk oder paradiesisch .. 42"
        time: "15:00"

    - name: "Erlesenes Kraut"
      photo: "/img/herbs.jpg"
      bio: "Wer sucht der findet, frisch von der Kulturwiese"
      company: "Mira"
      link:
        href: "https://de.wiktionary.org/wiki/Bl%C3%BCtensekt"
        text: "by Mira"
      presentation:
        title: "Wiesenkräuter Tour"
        description: "Schaut euch auf der Wiese genau um. Es gibt es so einiges zu entdecken und auch zu probieren. Aber immer Beachten: Kennen statt kotzen."
        time: "16:00"

    - name: "Musik Bühne"
      time: "17-22"

    - name: "Psychedelic Krautrock"
      photo: "/img/lucidvoid.jpg"
      bio: "Psychedelic Rock aus Darmstadt"
      company: "Psychedelic Krautrock"
      link:
        href: "https://lucidvoid.bandcamp.com"
        text: ">> Link"
      presentation:
        title: "Lucid Void"
        description: "Lucid Void starten den Live Musik Abend mit ihrem unverkennbaren Psychedelic Rock."
        time: "18:00"

    - name: "Rock'n'Soul Music"
      photo: "/img/tbsr.jpg"
      bio: "Finest Rock'n'Soul aus Darmstadt"
      company: "Rock'n'Soul"
      link:
        href: "https://badsugarrush.bandcamp.com"
        text: ">> Link"
      presentation:
        title: "Bad Sugar Rush"
        description: "Bad Sugar Rush packen ihre greatest Hits aus. Schnallt euch gut an, it's getting groovy .."
        time: "19:30"

    - name: "Psychedelic Jazz Rock"
      photo: "/img/karaba.jpg"
      bio: "Spacey Jazz Krautrock aus München"
      company: "Psycho Jazz Krautrock"
      link:
        href: "https://karaba-band.bandcamp.com"
        text: ">> Link"
      presentation:
        title: "Karaba"
        description: "Final wird uns Karaba zum gloreichen Abschluss ein wunderbar abgefreaktes Konzert abliefern."
        time: "20:45"

    - name: "Reise zum Sumpf"
      time: "22:00"

    - name: "Music From Out Of Space"
      photo: "/img/ztudfe.jpg"
      bio: "Unzuordbarer Alien Sound Mashup"
      company: "Freaky Alien Sounds"
      link:
        href: "https://ztudfe.bandcamp.com"
        text: ">> Link"
      presentation:
        title: "Zimtthinks und der faradayische Elefant"
        description: "Zum Transfer gibt es einen außerirdischen Walking Act zum Sumpf."
        time: "22:00"
