baseurl: "https://example.org/"
title: "Fourty Two Star"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "42* Fest"
  Description: "42 The Answer"
  Date: "24. August"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Kulturwiese"
  Address: "Schreberweg 21"
  City:  "Darmstadt"
  State: "Hessen"
  Images: ["/img/badge.jpg"]
  #GoogleMapsKey: "sSPBUTYT6NXrCBjv9"
  #https://maps.app.goo.gl/sSPBUTYT6NXrCBjv9

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - partners
    - sponsors
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "Info"
    location: "Location"
    speakers: "What's up"
    schedule: "Timetable"
    partners: "Prolog"
    sponsors: "Kontakt"
    #contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Register now!"
  #  link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Max"
      logo: "/img/contact.png"
      url: "https://mxklb.github.io/42star"
    - name: "Link"
      logo: "/img/qrcode.png"
      url: "https://mxklb.github.io/42star"

  # List of Partners
  Partners:
    text: "The ulitimate text/audio .. from A.Diroll"

  # The entire schedule
  Schedule:
    - name: "Starter"
      time: "13-18"

    - name: "Patch Some Cables"
      photo: "/img/slomosmo.png"
      bio: "Eine experimentelle Modular Synthesizer Chill Out Session"
      company: "Slomosmo"
      link:
        href: "https://soundcloud.com/slomosmo"
        text: "by Slomosmo"
      presentation:
        title: "Modular Lab"
        description: "Slomosmo & Friends kredenzen euch eine wundervoll elektronische Live Session. Sie machen Musik zur Untermalung des Live Paintings bis in den Nachmittag hinein."
        time: "13:00"

    - name: "37 Magics"
      photo: "/img/nick.png"
      bio: "Nick Marschalek vom Neuzeit Kollektive malt nice Bilder"
      company: "Nick Marschalek"
      link:
        href: "https://linktr.ee/nickmarschalek"
        text: "by Nick Marschalek"
      presentation:
        title: "Live Painting"
        description: "Nick Marschalek vom Neuzeit Kollektiv malt nice Bilder, begleitet von der Modular Synthesizer Session."
        time: "13:00"

    - name: "Print Some"
      photo: "/img/nino.jpg"
      bio: "Wer passende Klamotte mitbringt, kann bei Nino bedruckt werden"
      company: "Streetheartcolor"
      link:
        href: "https://www.instagram.com/streetheartcolor/"
        text: "by Streetheartcolor"
      presentation:
        title: "Nino's Siebdruck"
        description: "Eigene Klamotte mitbringen zum bedrucken, coole Siebe drucken."
        time: "13:00"

    - name: "Make A Button"
      photo: "/img/button.jpg"
      bio: "Bastel dir deinen individuellen 42* Button"
      company: "Meike"
      link:
        href: ""
        #text: "by Meike"
      presentation:
        title: "Button Workshop"
        description: "Ein 42* Button beantwortet generell auch alle Fragen."
        time: "13:00"

    - name: "Rituale"
      photo: "/img/orakel.png"
      bio: "Unser Orakel wird dir einen Weg weisen"
      company: "Michael Marquardt"
      link:
        href: "http://www.michael-marquardt.com/private.html"
        text: "by Michael Marquardt"
      presentation:
        title: "Orakel"
        description: "Wer nicht beim Orakel war, der kann es einfach nicht wissen."
        time: "13:00"

    - name: "Find Out What"
      photo: "/img/workshop2.jpg"
      bio: "Eine Option herauszufinden, was es herauszufinden gibt"
      company: "Mr. X"
      link:
        href: "https://en.wikipedia.org/wiki/37_(number)"
        text: "by Whatever 37"
      presentation:
        title: "Missing Workshop"
        description: "Finde heraus, was es schon immer herauszufinden galt."
        time: "13:00"

    - name: "Organic Materials"
      photo: "/img/land-art.jpg"
      bio: "Kreiere 100% biologisch abbaubare Kunst"
      company: "Mira"
      link:
        href: ""
        #text: "by Mira"
      presentation:
        title: "Land Art"
        description: "Erschaffe Kunst auf Basis natürliche auffindbarer Rohstoffen"
        time: "14:00"

    - name: "Erlesenes Kraut"
      photo: "/img/herbs.jpg"
      bio: "Wer sucht der findet, frisch von der Kulturwiese"
      company: "Mira"
      link:
        href: ""
        #text: "by Mira"
      presentation:
        title: "Kräuter Wanderung"
        description: "Schaut euch auf der Wiese genau um, es gibt dort einiges zu pflücken."
        time: "16:00"

    - name: "Theater Aktion"
      time: "14-16"

    - name: "Theater"
      photo: "/img/beyou.png"
      bio: "Theater Performance von A.Diroll & Johanna"
      company: "Be You Assemble"
      link:
        href: "https://www.p-stadtkultur.de/p-autoren/alex-diroll"
        text: "by BeYouuuu"
      presentation:
        title: "Be You"
        description: "@ Side Stage: Text zum Theaterstück.."
        time: "14:00"

    - name: "Poetry Slam"
      photo: "/img/42new.png"
      bio: "Und was hat das jetzt alles mit 5 mal 79 zu tun?"
      company: "Fourtytwostar"
      link:
        href: "https://simple.wikipedia.org/wiki/42_(answer)"
        text: "by FourtyTwoStar"
      presentation:
        title: "Poetry Slam"
        description: "@ Side Stage Text zum Slam.."
        time: "15:00"

    - name: "Live Musik"
      time: "18-22"

    - name: "Psychodelic Krautrock"
      photo: "/img/lucidvoid.jpg"
      bio: "Psychodelic Rock aus Darmstadt"
      company: "Psychodelic Krautrock"
      link:
        href: "https://lucidvoid.bandcamp.com"
        text: ">> Link"
      presentation:
        title: "Lucid Void"
        description: "In Darmstadt vermutlich allen Krautrockern bereits ein Begriff: Lucid Void starten den Live Musik Abend mit ihrem unverkennbaren Psychodelic Krautrock."
        time: "18:00"

    - name: "Soul & Rock Music"
      photo: "/img/tbsr.jpg"
      bio: "Finest Soul & Rock Music aus Darmstadt"
      company: "Soul & Rock"
      link:
        href: "https://badsugarrush.bandcamp.com"
        text: ">> Link"
      presentation:
        title: "The Bad Sugar Rush"
        description: "Die Band The Bad Sugar Rush spielen Ihre neusten Hits, man darf sehr gespannt sein. Put on your dancing shoes .."
        time: "19:30"

    - name: "Psychodelic Jazz Rock"
      photo: "/img/karaba.jpg"
      bio: "Spacey Jazz Krautrock aus München"
      company: "Psycho Jazz Krautrock"
      link:
        href: "https://karaba-band.bandcamp.com"
        text: ">> Link"
      presentation:
        title: "Karaba"
        description: "Die Band Karaba kommt wieder nach Darmstadt. Nachdem sie im Mai 2022 die Oettinger Villa gerockt haben, freuen wir uns sehr sie heute auf der Kuturwiese als gloreichen 42* Abschluss dabei zu haben."
        time: "21:00"
